"""Generate manuscript tables and a facts file from repository data (WORK_QUEUE Q11 step 2).

Run from this directory:  python scripts/build_tables.py [--check]

Writes:
  generated/tab_evidence_by_study.tex  per-study evidence records (P40-P45)
  generated/tab_crossenv.tex           cross-environment verification table
  generated/facts.json                 the numbers the prose relies on (read by check_manuscript_facts.py)
--check: fail if the generated files differ from the committed ones (so the tables cannot drift).
"""
import collections, json, subprocess, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
REPO = Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], cwd=HERE, text=True).strip())
sys.path.insert(0, str(REPO / "src"))
from engiproof.evidence_graph import audit_evidence_graph  # noqa: E402

STUDIES = ["P40", "P41", "P42", "P43", "P44", "P45"]
OUTCOMES = ["REPRODUCED", "COMPARED", "CONDITIONAL", "BLOCKED", "VERIFIED"]


def load(rel, default=None):
    p = REPO / rel
    return json.loads(p.read_text(encoding="utf-8")) if p.is_file() else default


def study_rows():
    rows = []
    for pid in STUDIES:
        s = load(f"engiproof/studies/{pid}/study.json")
        comp = collections.Counter(c["status"] for c in s.get("comparisons", []))
        disc = collections.Counter(d["status"] for d in s.get("discrepancies", []))
        dec = (load(f"engiproof/studies/{pid}/discrepancy_decisions.json", {"decisions": []}) or {}).get("decisions", [])
        g = audit_evidence_graph(pid)
        ing = load(f"engiproof/studies/{pid}/ingestion_summary.json")["selected_targets"]
        rows.append({"study": pid, "tools": len(s.get("tools", [])), "comparisons": dict(comp),
                     "discrepancies": dict(disc), "decisions": [d["disposition"] for d in dec],
                     "graph_nodes": g["node_count"], "graph_edges": g["edge_count"], "graph_coverage": g["coverage_fraction"],
                     "ready": ing["ready_count"], "selected": ing["count"],
                     "evidence_status": s.get("evidence_status"),
                     # framework default when the manifest has no field (core.py / evidence_graph.py)
                     "qualification": s.get("qualification", "NOT_CLAIMED"),
                     "qualification_field_present": "qualification" in s,
                     "graph_qualification": g["qualification"]})
    return rows


def all_discrepancies():
    out = []
    for d in sorted((REPO / "engiproof/studies").iterdir()):
        s = load(f"engiproof/studies/{d.name}/study.json")
        if s:
            out += s.get("discrepancies", [])
    return out


ABBR = {"ACCEPTED_WITH_RATIONALE": "A", "BOUNDED": "B", "DEFERRED": "D", "RESOLVED": "R"}


def tab_evidence(rows):
    L = [r"% Generated by scripts/build_tables.py from repository data. Do not edit by hand.",
         r"\begin{tabular}{lrrrrrrrcrc}", r"\toprule",
         r"& & \multicolumn{4}{c}{Comparison outcomes} & \multicolumn{2}{c}{Discrepancies} & & Graph & \\",
         r"\cmidrule(lr){3-6}\cmidrule(lr){7-8}",
         r"Study & Tools & \texttt{REPR.} & \texttt{COMP.} & \texttt{COND.} & \texttt{BLOCK.} & \texttt{OPEN} & \texttt{OBS.} & Ready & Nodes & Decisions \\",
         r"\midrule"]
    for r in rows:
        c, d = r["comparisons"], r["discrepancies"]
        dec = ", ".join(f"{n}{ABBR[k]}" for k, n in sorted(collections.Counter(r["decisions"]).items())) or "--"
        L.append(f"{r['study']} & {r['tools']} & {c.get('REPRODUCED', 0)} & {c.get('COMPARED', 0)} & {c.get('CONDITIONAL', 0)} & "
                 f"{c.get('BLOCKED', 0)} & {d.get('OPEN', 0)} & {d.get('OBSERVED', 0)} & {r['ready']}/{r['selected']} & {r['graph_nodes']} & {dec} \\\\")
    tot = lambda f: sum(f(r) for r in rows)
    L.append(r"\midrule")
    L.append(f"Total & {tot(lambda r: r['tools'])} & {tot(lambda r: r['comparisons'].get('REPRODUCED', 0))} & {tot(lambda r: r['comparisons'].get('COMPARED', 0))} & "
             f"{tot(lambda r: r['comparisons'].get('CONDITIONAL', 0))} & {tot(lambda r: r['comparisons'].get('BLOCKED', 0))} & "
             f"{tot(lambda r: r['discrepancies'].get('OPEN', 0))} & {tot(lambda r: r['discrepancies'].get('OBSERVED', 0))} & "
             f"{tot(lambda r: r['ready'])}/{tot(lambda r: r['selected'])} & & {tot(lambda r: len(r['decisions']))} \\\\")
    L += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(L)


def tab_crossenv(rec):
    classes = ["IDENTICAL", "BYTE_ONLY", "ENVIRONMENT_METADATA", "NUMERICAL_NONMATERIAL", "NUMERICAL_MATERIAL", "MATERIAL_NON_NUMERIC"]
    arch = {"x86_64": "x86-64", "AMD64": "x86-64", "arm64": "arm64"}
    osn = {"Darwin": "macOS"}
    order = {"Linux": 0, "Windows": 1, "Darwin": 2}
    envs = sorted(rec["environments"], key=lambda e: (order.get(e["os"], 9), e["python"]))
    L = [r"% Generated by scripts/build_tables.py from docs/CROSS_ENVIRONMENT_VERIFICATION.json. Do not edit by hand.",
         r"\begin{tabular}{llllrrrrrr}", r"\toprule",
         r"OS & Arch & Python & NumPy & \texttt{IDENT.} & \texttt{BYTE} & \texttt{ENV} & \texttt{NUM\_NM} & \texttt{NUM\_M} & \texttt{MAT\_NN} \\",
         r"\midrule"]
    for e in envs:
        t = e["classification_totals"]
        L.append(f"{osn.get(e['os'], e['os'])} & {arch.get(e['machine'], e['machine'])} & {e['python']} & {e['numpy']} & "
                 + " & ".join(str(t.get(c, 0)) for c in classes) + r" \\")
    L += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(L)


def result_qualifications():
    """Qualification values recorded in P40-P45 result JSON files, and files that carry none."""
    def walk(o):
        if isinstance(o, dict):
            return [v for k, v in o.items() if k == "qualification" and isinstance(v, str)] + [x for v in o.values() for x in walk(v)]
        if isinstance(o, list):
            return [x for v in o for x in walk(v)]
        return []
    values, without = set(), []
    for pid in STUDIES:
        for f in sorted((REPO / "papers" / pid / "results").glob("*.json")):
            q = walk(json.loads(f.read_text(encoding="utf-8")))
            values.update(q)
            if not q:
                without.append(f.relative_to(REPO).as_posix())
    return sorted(values), without


def facts(rows, rec):
    comp = collections.Counter(); disc = collections.Counter()
    for r in rows:
        comp.update(r["comparisons"]); disc.update(r["discrepancies"])
    decisions = [d for pid in sorted(p.name for p in (REPO / "engiproof/studies").iterdir())
                 for d in (load(f"engiproof/studies/{pid}/discrepancy_decisions.json", {"decisions": []}) or {}).get("decisions", [])]
    mapping = load("engiproof/contracts/discrepancy_taxonomy_mapping.json")
    tax = load("engiproof/contracts/contracts.json")["contracts"]["discrepancy_taxonomy"]
    review = (REPO / "publication/PAPER_A_ENGIPROOF/PAPER_A_READINESS_REVIEW.md").read_text(encoding="utf-8")
    import re
    failures = sorted({int(m) for m in re.findall(r"^\| F(\d+) \|", review, flags=re.M)})
    return {
        "comparisons_total": sum(comp.values()), "comparisons": dict(comp),
        "discrepancies_paper_a": sum(disc.values()), "discrepancies_paper_a_by_status": dict(disc),
        "discrepancies_repository": len(all_discrepancies()),
        "decisions_total": len(decisions), "decisions_by_disposition": dict(collections.Counter(d["disposition"] for d in decisions)),
        "taxonomy_categories": len(tax["categories"]), "taxonomy_loci": len(tax["loci"]),
        "taxonomy_approved": sum(1 for r in mapping["records"] if (r.get("reviews") or [{}])[-1].get("decision") == "APPROVED"),
        "graph_nodes_min": min(r["graph_nodes"] for r in rows), "graph_nodes_max": max(r["graph_nodes"] for r in rows),
        "graph_coverage_all": sorted({r["graph_coverage"] for r in rows}),
        "readiness": {r["study"]: [r["ready"], r["selected"]] for r in rows},
        "evidence_status": sorted({r["evidence_status"] for r in rows}), "qualification": sorted({r["qualification"] for r in rows}),
        "qualification_by_study": {r["study"]: r["qualification"] for r in rows},
        "graph_qualification_by_study": {r["study"]: r["graph_qualification"] for r in rows},
        "manifests_without_qualification_field": [r["study"] for r in rows if not r["qualification_field_present"]],
        "result_qualification_values": result_qualifications()[0],
        "result_files_without_qualification_field": result_qualifications()[1],
        "failure_modes": len(failures), "failure_ids_contiguous": failures == list(range(1, len(failures) + 1)),
        "crossenv_environments": len(rec["environments"]), "crossenv_studies": sorted({e["studies"] for e in rec["environments"]}),
        "crossenv_material": sum(e["classification_totals"].get("NUMERICAL_MATERIAL", 0) + e["classification_totals"].get("MATERIAL_NON_NUMERIC", 0) for e in rec["environments"]),
    }


def main():
    rows = study_rows()
    rec = load("docs/CROSS_ENVIRONMENT_VERIFICATION.json")
    outputs = {"generated/tab_evidence_by_study.tex": tab_evidence(rows), "generated/tab_crossenv.tex": tab_crossenv(rec),
               "generated/facts.json": json.dumps(facts(rows, rec), indent=2, sort_keys=True) + "\n"}
    check = "--check" in sys.argv
    stale = []
    for rel, text in outputs.items():
        p = HERE / rel
        if check:
            if not p.is_file() or p.read_text(encoding="utf-8") != text:
                stale.append(rel)
        else:
            p.parent.mkdir(exist_ok=True)
            p.write_text(text, encoding="utf-8")
    if stale:
        print("STALE:", ", ".join(stale)); sys.exit(1)
    print("OK" if check else "written: " + ", ".join(outputs))


if __name__ == "__main__":
    main()
