"""Regenerate sections/a_claim_evidence.tex from publication/PAPER_A_ENGIPROOF/CLAIM_EVIDENCE_MATRIX.md.

Run from this directory:  python scripts/build_claim_appendix.py

Appendix A lists ID, claim and status only. The matrix's evidence column and its authoring
notes ("Constraint for the manuscript") stay in the repository matrix and are not printed.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
MATRIX = HERE.parents[2] / "CLAIM_EVIDENCE_MATRIX.md"
OUT = HERE / "sections" / "a_claim_evidence.tex"
SPECIAL = {"\\": r"\textbackslash{}", "&": r"\&", "%": r"\%", "$": r"\$", "#": r"\#", "_": r"\_",
           "{": r"\{", "}": r"\}", "~": r"\textasciitilde{}", "^": r"\textasciicircum{}"}
UNICODE = {"≤": r"$\le$", "≥": r"$\ge$", "≈": r"$\approx$", "×": r"$\times$", "→": r"$\rightarrow$", "θ": r"$\theta$",
           "Δ": r"$\Delta$", "“": "``", "”": "''", "’": "'", "…": r"\ldots{}", "–": "--", "—": "---", "·": r"$\cdot$"}


def esc(text: str) -> str:
    out = []
    for i, part in enumerate(text.split("`")):
        s = "".join(SPECIAL.get(c, c) for c in part)
        for k, v in UNICODE.items():
            s = s.replace(k, v)
        s = re.sub(r"\*\*(.+?)\*\*", r"\\textbf{\1}", s)
        out.append(r"\texttt{" + s + "}" if i % 2 else s)
    # Allow line breaks after underscores and slashes in long identifiers and paths.
    return "".join(out).replace(r"\_", r"\_\allowbreak{}").replace("/", r"/\allowbreak{}")


def rows():
    for line in MATRIX.read_text(encoding="utf-8").splitlines():
        if re.match(r"^\| PA-\d\d ", line):
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            yield cells[0], cells[1], cells[2]


def main() -> None:
    lines = [r"% Generated by scripts/build_claim_appendix.py from CLAIM_EVIDENCE_MATRIX.md. Do not edit by hand.",
             r"\section{Claim--evidence matrix}", r"\label{app:claims}",
             r"Repository evidence for each claim is listed in the tracked claim--evidence matrix (\texttt{CLAIM\_\allowbreak{}EVIDENCE\_\allowbreak{}MATRIX.md} in the Paper~A publication folder). Status vocabulary: SUPPORTED, PARTIALLY\_SUPPORTED, NOT\_SUPPORTED\_YET, OUT\_OF\_SCOPE.",
             r"{\footnotesize\setlength{\tabcolsep}{3pt}", r"\begin{longtable}{>{\raggedright\arraybackslash}p{0.08\linewidth}>{\raggedright\arraybackslash}p{0.64\linewidth}>{\raggedright\arraybackslash}p{0.2\linewidth}}",
             r"\toprule ID & Claim & Status \\ \midrule \endfirsthead",
             r"\toprule ID & Claim & Status \\ \midrule \endhead"]
    rs = list(rows())
    for i, (cid, claim, status) in enumerate(rs):
        # "\\*" forbids a page break after the penultimate row, so the last row never stands alone.
        end = "\\\\*" if i == len(rs) - 2 else "\\\\"
        lines.append(f"{cid} & {esc(claim)} & {esc(status)} {end}")
    lines += [r"\bottomrule", r"\end{longtable}", "}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
